<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Staff;
use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findModuleLeaderForStaff($staff)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
          SELECT p.moduleLeaderHrs, p.internalModeratorHrs, p.name
          FROM AppBundle:Module p
          WHERE (p.moduleLeader = :staff)
          ')
            ->setParameter('staff', $staff);

        $allocations = $query->getResult();
        return $allocations;

    }

    public function findInternalModeratorForStaff($staff)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
          SELECT p.moduleLeaderHrs, p.internalModeratorHrs, p.name
          FROM AppBundle:Module p
          WHERE (p.internalModerator= :staff)
          ')
            ->setParameter('staff', $staff);

        $allocations = $query->getResult();
        return $allocations;

    }

    public function findModuleLeaderTotal($staff)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
          SELECT SUM(p.moduleLeaderHrs) as moduleLeaderHrsTotal
          FROM AppBundle:Module p
          WHERE (p.moduleLeader = :staff)
          ')
            ->setParameter('staff', $staff);

        $totals = $query->getOneOrNullResult();
        return $totals;


    }

    public function findinternalModeratorTotal($staff)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
          SELECT SUM(p.internalModeratorHrs) as internalModeratorHrsTotal
          FROM AppBundle:Module p
          WHERE (p.internalModerator = :staff)
          ')
            ->setParameter('staff', $staff);

        $totals = $query->getOneOrNullResult();
        return $totals;

    }
}
